mysql:
  1:
    dbname: myplay
    user: root
    password: 123456
    host: localhost:13306
    slave:

redis:
  1:
    dbname: myplay
    db: 1
    prefix: myplay
    user: default
    password: 123456
    host: localhost:16379

etcd:
  topic: poker_server/local/etcd
  endpoints:
    - http://localhost:12379

nats:
  topic: poker_server/local/nats
  endpoints: localhost:14222

table:
  is_remote: false
  ext: .conf
  path: ./data
  endpoints:
    - http://localhost:12379

common:
  env: develop #develop, beta, release
  is_open_pprof: true
  token_key: gH7%kL9!qW2#sD4*FpV6&nZ8@xJ0^yT1
  aes_key: 1234567890123456

client:
  1:
    log_level: trace # info, debug, warn, error, fatal
    log_path: ./log
    ip: localhost
    port: 10101

auth:
  1:
    log_level: trace  # info, debug, warn, error, fatal
    log_path: ./log
    ip: localhost
    port: 10001

gate:
  1:
    router_ttl: 1800
    discovery_ttl: 20
    log_level: trace  # info, debug, warn, error, fatal
    log_path: ./log
    ip: localhost
    port: 10101
  2:
    router_ttl: 1800
    discovery_ttl: 20
    log_level: trace  # info, debug, warn, error, fatal
    log_path: ./log
    ip: localhost
    port: 10102